nome = input("Digite seu primeiro nome: ")
sobremone = input("Digite seu sobnome: ")
idade = int(input("Digite sua idade: "))
altura = float(input("Digite sua altura: "))
print("Ola",nome,sobremone,", você tem",idade,"anos e uma estatura de",altura,"metros.")